console.log(a) // não retorna erro pois a variável sofre um içamento. É como se tivesse um var a antes.
var a = 2
console.log(a)